image:
  name: antora/antora:3.0.0
# workaround for @antora/lunr-extension
variables:
  NODE_OPTIONS: '--max-old-space-size=4096'
before_script:
  - npm i
pages:
  stage: deploy
  cache:
    paths:
      - .cache/
  script:
    - npx antora --cache-dir .cache/antora --redirect-facility gitlab antora-playbook.yml
  artifacts:
    paths:
      - public/