site:
  title: Документация Docsvision
  url: http://help.docsvision.com/
  start_page: ROOT:ROOT:general-description.adoc
  robots: allow
urls:
#  latest_version_segment: latest
#  latest_version_segment_strategy: redirect:to
  latest_prerelease_version_segment: dev
  html_extension_style: indexify
content:
  branches: 'dev'
  edit_url: ~
  sources:
    - url: https://github.com/Docsvision/WebC-Antora.git
#    - url: https://github.com/Docsvision/Worker-Antora.git
#    - url: https://github.com/Docsvision/Platform-Antora.git
#    - url: https://github.com/Docsvision/WebAC-Antora.git
#    - url: https://github.com/Docsvision/Install-Guide-Antora.git
#    - url: https://github.com/Docsvision/Designers-And-Directories-Antora.git
#    - url: https://github.com/Docsvision/System-Antora.git
#    - url: https://github.com/Docsvision/Approval-Designer-Antora.git
#    - url: https://github.com/Docsvision/Base-Objects-Antora.git
#    - url: https://github.com/Docsvision/Platform-Upgrade-Antora.git
#    - url: https://github.com/Docsvision/Engineer-Antora.git
#    - url: https://github.com/Docsvision/Programmer-Antora.git
git:
  credentials:
    path: ~/.git-credentials
ui:
  bundle:
    url: ./build/ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ search.html ]
    - path: search.html
      contents: |
        <!DOCTYPE html>
        <html lang="ru">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <title>Поиск по документации Docsvision :: Документация Docsvision</title>
            <link rel="canonical" href="/search.html">
            <meta name="generator" content="Antora 2.3.4">
            <link rel="stylesheet" href="/_/css/site.css">
            <script>var uiRootPath = '/_'</script>
        	<script async src="/_/js/vendor/fess-ss.min.js"></script>
          </head>
          <body class="article">
        <header class="header">
          <nav class="navbar">
            <div class="navbar-brand">
              <a class="navbar-item" href="http://help.docsvision.com">Документация Docsvision</a>
              <button class="navbar-burger" data-target="topbar-nav">
                <span></span>
                <span></span>
                <span></span>
              </button>
            </div>
            <div id="topbar-nav" class="navbar-menu">
              <div class="navbar-end">
                <div class="navbar-item hide-for-print">
               	  <form action="/search.html" method="get">
               		<input type="text" name="q" placeholder="Поиск">
               		<input type="submit" value="Поиск">
               	  </form>
                </div>
                <a class="navbar-item" href="https://docsvision.com/">Docsvision.com</a>
                <div class="navbar-item has-dropdown is-hoverable">
                  <div class="navbar-link">Дополнительно</div>
                  <div class="navbar-dropdown is-right">
                  <a class="navbar-item" href="https://docsvision.github.io/WebClient-JsDocApi/">WebClient JsDocApi</a>
                  <a class="navbar-item" href="https://github.com/Docsvision/WebClient-Samples">Docsvision Web-клиент. Примеры разработки.</a>
                </div>
            </div>
          </nav>
        </header>
        <div class="body">
        <article class="doc">
              <h1 class="page">Поиск по документации</h1>
        <div class="paragraph">
        <script>
          (function() {
            var fess = document.createElement('script');
            fess.type = 'text/javascript';
            fess.async = true;
            // Set the URL of FSS JS to src
            fess.src = '/_/js/vendor/fess-ss.min.js';
            fess.charset = 'utf-8';
            fess.setAttribute ('id', 'fess-ss');
            // Set the URL of Fess search API to fess-url
            fess.setAttribute ('fess-url', 'http://help.docsvision.com:8080/json');
            var s = document.getElementsByTagName ('script') [0];
            s.parentNode.insertBefore (fess, s);
          }) ();
        </script>
        <fess:search></fess:search>
        </div>
        </article>
        </div>
        </main>
        <footer class="footer">
          <p>© 2001 — <script>document.write(new Date().getFullYear())</script> «ДоксВижн»</p>
        </footer>
        <script src="/_/js/site.js"></script>
        <script async src="/_/js/vendor/highlight.js"></script>
          </body>
        </html>
asciidoc:
  attributes:
    sectids: ''
    sectanchors: ''
    icons: font
    page-pagination: ''
    toclevels: 10
    experimental: ''
    source-highlighter: highlightjs
    idprefix: ''
    idseparator: '-'
    toc-title: 'Содержание'
    figure-caption: 'Рисунок'
    table-caption: 'Таблица'
    appendix-caption: 'Приложение'
    example-caption: 'Пример'
    kroki-default-format: 'svg'
    kroki-fetch-diagram: 'true'
    cns: 'Консоль настройки Docsvision'
    dv: 'Docsvision'
    root-cert: 'Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователя.footnote:[Например, корневой сертификат КриптоПро]@'
    pl: 'Платформа'
    wincl: 'Windows-клиент'
    wc: 'Web-клиент'
    sss: 'Docsvision 5.5 Storage Server'
    fts: 'Docsvision 5.5 Full-Text indexing Service'
    wfs: 'Docsvision 5.5 Workflow Server'
    fss: 'Docsvision 5.5 File Service'
    wacs-g: 'Docsvision ManagementConsole Administrators'
    wacss-g: 'Docsvision SettingsService Administrators'
    wacs: 'Docsvision ManagementConsole Service'
    wacss: 'Docsvision SettingsService Service'
    ws: 'фоновых операций'
    kvr: 'Конструктор Web-разметок'
    ad: 'Конструктор согласований'
    ud: 'Управление документами'
    bo: 'Базовые объекты'
    wf: 'Управление процессами@'
    es: 'Elasticsearch'
    hklm-dv: 'HKEY_LOCAL_MACHINE\SOFTWARE\Docsvision'
    hklm: 'HKEY_LOCAL_MACHINE'

  extensions:
      - asciidoctor-kroki
output:
  dir: wwwroot
runtime:
  fetch: true
